Temporarily depend on heroku-buildpack-multi

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -19,34 +19,57 @@ cd "$2"
 
 # Create a dummy version of git
 mkdir tools
-cat > ./tools/git <<EOF
+cat > ./tools/git << 'EOF'
 #!/bin/sh
-echo "Skipping git command:" "$@"
+echo "Skipping git command: git" "$@"
 EOF
 chmod +x ./tools/git
+PATH="$2/tools:$PATH"
 
 # Make sure we have the correct Rust binaries and set up PATH.
-if [ -d rust-cache-$VERSION ]; then
-  echo "-----> Using Rust version $VERSION"
-else
-  echo "-----> Downloading Rust version $VERSION binaries from $URL"
+#if [ -d rust-cache-$VERSION ]; then
+#  echo "-----> Using Rust version $VERSION"
+#else
+#  echo "-----> Downloading Rust version $VERSION binaries from $URL"
+#
+#  rm -f rust.tar.gz
+#  rm -rf rust-cache-*
+#  curl -o rust.tar.gz "$URL"
+#
+#  echo "-----> Extracting Rust binaries"
+#
+#  mkdir rust-cache-$VERSION
+#  tar xzf rust.tar.gz -C rust-cache-$VERSION
+#  rm -r rust.tar.gz
+#fi
+#rust_path=`ls -1d "$2/rust-cache-$VERSION/"*"/bin"`
+#if [ ! -x "$rust_path/rustc" ]; then
+#    echo "failed: Cannot find rust binaries at $rust_path"
+#    exit 1
+#fi
+#PATH="$rust_path:$PATH"
 
-  rm -f rust.tar.gz
-  rm -rf rust-cache-*
-  curl -o rust.tar.gz "$URL"
+echo "-----> Installing support packages"
 
-  echo "-----> Extracting Rust binaries"
+sudo sh -c 'echo "deb http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu lucid main\ndeb-src http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu lucid main\n" > /etc/apt/sources.list.d/toolchain.list'
+gpg --keyserver wwwkeys.pgp.net --recv-keys 1E9377A2BA9EF27F
+gpg --armor --export 1E9377A2BA9EF27F | sudo apt-key add -
+sudo apt-get update
+sudo apt-get -y install libstdc++6
 
-  mkdir rust-cache-$VERSION
-  tar xzf rust.tar.gz -C rust-cache-$VERSION
-  rm -r rust.tar.gz
-fi
-rust_path=`ls -1d "$2/rust-cache-$VERSION/"*"/bin"`
-if [ ! -x "$rust_path/rustc" ]; then
-    echo "failed: Cannot find rust binaries at $rust_path"
-    exit 1
-fi
-PATH="$rust_path:$2/tools:$PATH"
+echo "-----> Downloading Rust binaries"
+
+curl -o rust.tar.gz https://s3.amazonaws.com/rust-builds/rust-nightly-x86_64-unknown-linux-gnu.tar.gz
+
+echo "-----> Extracting Rust binaries"
+
+tar xzf rust.tar.gz
+cd rust-nightly-x86_64-unknown-linux-gnu/
+
+echo "-----> Installing Rust binaries"
+
+sudo ./install.sh
+rm -rf rust.tar.gz rust-nightly-x86_64-unknown-linux-gnu/
 
 # Build the actual application.
 echo "-----> Building application"
